Repository Sidenow-Team2/freshgreenish-back, pull requests merged in 2023-09, with the labels that each got.

#20 정렬 오류 수정 및 삭제 복구 오류 수정
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/controller/ProductController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/entity/Product.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/repository/CustomProductRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/repository/ProductRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/service/ProductDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/service/ProductService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/exception/ExceptionCode.java
Labels: 🕷 Bug, 🛠 Refactoring

#27 찜하기 기능 1차 구현
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/likes/controller/LikesController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/likes/dto/GetLikesList.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/likes/dto/WrapLikes.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/likes/entity/Likes.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/likes/repository/CustomLikesRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/likes/repository/LikesRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/likes/repository/LikesRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/likes/service/LikesService.java
Labels: 👨‍💻 Feature

#28 문의 질문 기능 1차 구현
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/controller/QuestionController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/dto/GetQuestionDetail.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/dto/GetQuestionOnMyPage.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/dto/GetQuestionOnQnAPage.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/dto/PostQuestion.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/entity/Question.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/entity/QuestionAnswerStatus.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/repository/CustomQuestionRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/repository/QuestionRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/service/QuestionDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/service/QuestionService.java
Labels: 👨‍💻 Feature

#30 리뷰 기능 1차 구현
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/controller/ReviewController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/dto/GetReviewOnMyPage.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/dto/GetReviewOnProductDetail.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/dto/PostReview.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/dto/WrapReviewLikes.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/entity/Review.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/repository/CustomReviewRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/repository/ReviewLikesRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/repository/ReviewRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/service/ReviewDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/service/ReviewService.java
Labels: 👨‍💻 Feature

#31 상품 예외처리 추가 및 delete 여부 조회, likeCount 수정 메서드 추가
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/entity/Product.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/repository/CustomProductRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/repository/ProductRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/service/ProductDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/service/ProductService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/exception/ExceptionCode.java
Labels: 👨‍💻 Feature, 🛠 Refactoring

#29 문의 답변 기능 1차 구현
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/answer/controller/AnswerController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/answer/dto/GetAnswerDetail.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/answer/dto/PostAnswer.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/answer/entity/Answer.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/answer/repository/AnswerRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/answer/repository/CustomAnswerRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/answer/service/AnswerDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/answer/service/AnswerService.java
Labels: 👨‍💻 Feature

#32 상품 이미지 등록/수정 기능 구현
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/controller/ProductController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/dto/EditProduct.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/entity/Product.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/repository/CustomProductRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/repository/ProductRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/service/ProductDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/service/ProductService.java
Labels: 👨‍💻 Feature

#33 리뷰 이미지 등록/수정/삭제 기능 구현
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/controller/ReviewController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/dto/EditReview.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/dto/GetReviewOnMyPage.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/dto/GetReviewOnProductDetail.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/dto/ReviewImageVO.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/entity/Review.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/repository/ReviewRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/service/ReviewDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/review/service/ReviewService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/exception/ExceptionCode.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/file/FileHandler.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/file/UploadFile.java
Labels: 👨‍💻 Feature, 🛠 Refactoring

#37 장바구니 1차 기능 구현
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/controller/BasketController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/dto/DeleteBasket.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/dto/GetBasket.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/dto/PostBasket.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/dto/TotalPriceInfo.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/dto/WrapBasket.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/entity/Basket.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/entity/ProductBasket.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/repository/BasketRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/repository/BasketRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/repository/CustomBasketRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/repository/ProductBasketRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/service/BasketDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/basket/service/BasketService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/entity/Product.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/repository/CustomProductRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/repository/ProductRepositoryImpl.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/service/ProductDbService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/question/service/QuestionService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/exception/ExceptionCode.java
Labels: 👨‍💻 Feature, 🛠 Refactoring

#38 배송지 조회/등록/수정/삭제 개발
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/address/controller/AddressController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/address/dto/GetAddressDTO.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/address/dto/PostAddressDTO.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/address/entity/Address.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/address/repository/AddressRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/address/service/AddressService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/product/controller/ProductController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/config/SecurityConfig.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/exception/ExceptionCode.java
  freshgreenish/src/main/resources/application.yml
  freshgreenish/src/main/resources/templates/addressform.html
Labels: 👨‍💻 Feature

#42 마이페이지: 개인정보 수정 기능
  freshgreenish/.gitignore
  freshgreenish/build.gradle
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/address/entity/Address.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/address/repository/AddressRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/controller/MyInfoController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/controller/UserController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/dto/MyInfoDTO.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/dto/UserImageVO.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/entity/User.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/repository/MyInfoRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/repository/UserRepository.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/service/MyInfoService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/domain/user/service/UserImageFileHandler.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/config/SecurityConfig.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/config/auth/dto/OAuthAttributes.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/config/mail/controller/MailController.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/config/mail/service/MailService.java
  freshgreenish/src/main/java/com/sidenow/freshgreenish/global/exception/ExceptionCode.java
  freshgreenish/src/main/resources/templates/home.html
Labels: 👨‍💻 Feature
